name: verify

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          cache-pip: true

      - name: oj-resolve
        uses: competitive-verifier/actions/oj-resolve@v2
        with:
          output-path: verify_files.json
          include: verify/

      - name: Upload verify_files.json
        uses: competitive-verifier/actions/upload-verify-artifact@v2
        with:
          file: verify_files.json

  verify:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      SPLIT_SIZE: "8"
    strategy:
      matrix:
        index: ["0", "1", "2", "3", "4", "5", "6", "7"]
    steps:
      - uses: actions/checkout@v4

      - name: Download verify_files.json
        uses: competitive-verifier/actions/download-verify-artifact@v2

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          python-version: pypy3.10
          cache-pip: true

      - name: Install PyRival
        run: pip install .

      - name: Verify
        uses: competitive-verifier/actions/verify@v2
        with:
          write-summary: true
          tle: 5
          timeout: 300
          destination: ${{runner.temp}}/result.json
          split-size: ${{ env.SPLIT_SIZE }}
          split-index: ${{ matrix.index }}
          check: true
